/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rjstanford.util;

import org.junit.Test;
import static org.junit.Assert.*;

public class KeyUtilTest {


    @Test public void testLong() {
        assertEquals("XUY38TKDFDOI6", KeyUtil.toString(1L));
        assertEquals(1, (long) KeyUtil.toLong("XUY38TKDFDOI6"));
        assertEquals("ZMD5GTHUJT7NY", KeyUtil.toString(123L));
        assertEquals(123, (long) KeyUtil.toLong("ZMD5GTHUJT7NY"));
    }

    @Test public void testInt() {
        assertEquals("5G9L5AK", KeyUtil.toString(1));
        assertEquals(1, (int) KeyUtil.toInteger("5G9L5AK"));
        assertEquals("YHZ2Q6Y", KeyUtil.toString(123));
        assertEquals(123, (int) KeyUtil.toInteger("YHZ2Q6Y"));
    }

    @Test public void testShort() {
        assertEquals("27YN", KeyUtil.toString((short)1));
        assertEquals(1, (int) KeyUtil.toShort("27YN"));
        assertEquals("Y8GV", KeyUtil.toString((short)123));
        assertEquals(123, (short) KeyUtil.toShort("Y8GV"));
    }

    @Test public void testCleanup() {
        assertEquals(123, (int) KeyUtil.toInteger("YHZ2Q6Y"));
        assertEquals(123, (int) KeyUtil.toInteger("YH-Z2-Q6-Y"));
        assertEquals(123, (int) KeyUtil.toInteger("yh-Z2-Q6-Y"));
        assertEquals(1, (long) KeyUtil.toLong("XUY38TKDFDOI6"));
        assertEquals(1, (long) KeyUtil.toLong("XUY38TKDFD016"));
    }


}
