name: Pull Request Merge

on:
  pull_request:
    types:
      - closed

jobs:
  Library-Deploy:
    if: github.event.pull_request.merged
    uses: rjstanford/github/.github/workflows/gradle-library-deploy.yml@main
