name: Library Deploy

on:
  pull_request:
    types:
      - closed

jobs:
  Deploy:
    if: github.event.pull_request.merged
    uses: rjstanford/actions/.github/workflows/gradle-library-deploy.yml@main
