name: Pull Request Activity

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  Test:
    name: Unit Test
    uses: rjstanford/github/.github/workflows/gradle-test.yml@main
